name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pytest selenium webdriver-manager

    - name: Run unit tests with pytest
      run: pytest tests --junitxml=results/unit-tests.xml

    - name: Start Flask app in background
      run: |
        cd web
        nohup python app_web.py &

    - name: Wait for server
      run: sleep 5

    - name: Run Selenium tests
      env:
        SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
      run: |
        python tests/test_app_web.py

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: results/
